version: '3'
services:
  toreador-vue:
    image: toreador-vue
    build: .
    command: npm run serve
    ports:
      - "3000:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
